# Importing Package

In [1]:
import sys
import numpy as np 
import matplotlib
import time

### Matrix multiplication of multiple input for one layer 

In [25]:
inputs = [[ 1.0, 2.0, 3.0, 2.5],
          [ 2.0, 5.0,-1.0, 2.0],
          [-1.5, 2.7, 3.3,-0.8]]

weights =[[ 0.2 ,  0.8 ,-0.5 , 1.0 ],
          [ 0.5 , -0.91, 0.26,-0.5 ],
          [-0.26, -0.27, 0.17, 0.87]]

biases = [2,3,0.5]

output = np.dot(np.array(inputs),np.array(weights).T) + np.array(biases)

print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


### Multilayer Matrix multiplication

In [27]:
inputs = [[ 1.0, 2.0, 3.0, 2.5],
          [ 2.0, 5.0,-1.0, 2.0],
          [-1.5, 2.7, 3.3,-0.8]]

weights1=[[ 0.2 ,  0.8 ,-0.5 , 1.0 ],
          [ 0.5 , -0.91, 0.26,-0.5 ],
          [-0.26, -0.27, 0.17, 0.87]]

weights2=[[ 0.1 , -0.14, 0.5 ],
          [-0.5 ,  0.12,-0.33],
          [-0.44,  0.70, 0.13]]

biases1 = [ 2 ,3, 0.5]
biases2 = [-1 ,2,-0.5]

layer1 = np.dot(np.array(inputs),np.array(weights1).T)+biases1
layer2 = np.dot(layer1,np.array(weights2).T)+biases2
layer2

array([[ 0.5031 , -1.04185, -1.45495],
       [ 0.2434 , -2.7332 , -5.657  ],
       [-0.99314,  1.41254, -0.38132]])

### Making a class

In [36]:
x=[[ 1.0, 2.0, 3.0, 2.5],
   [ 2.0, 5.0,-1.0, 2.0],
   [-1.5, 2.7, 3.3,-0.8]]

np.random.seed(0)

class Layer_dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights = 0.01*np.random.randn(n_inputs,n_neurons)
        self.bias    = np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights) + self.bias
        
layer1= Layer_dense(4,5)
layer2= Layer_dense(5,1)

layer1.forward(x)
layer2.forward(layer1.output)

In [37]:
layer2.output

array([[0.00080817],
       [0.00117231],
       [0.0020913 ]])